### PR TITLE
add sim/m5stack

### PR DESCRIPTION
**Pull request by NW-Lab**
Hello 

I would like to make a pull request to use the M5Stack Simulator provided with Moodable sdk 4.5.

Thank you.

### CODE REVIEW

**Comment by NW-Lab** [comment]
Hello
Also added moddable_display_4.
Thank you.

**Comment by NW-Lab** [comment]
Hello
 
Added esp32/esp32c6_cdc, esp32/esp32h2_cdc, and esp32/m5nanoc6.

Thank you.

**Comment by ralphwetzel** [comment]
Thank you!

**Comment by phoddie** [comment]
Thanks, @ralphwetzel!

**Comment by NW-Lab** [comment]
@ralphwetzel  
Thank you.

**Pull request merged**
