### PR TITLE
Corrected support for NRF52, NodeRED3.1, and unregistered Platforms.

### PR DESCRIPTION
**Pull request by NextWorldLab**
Hello,

This PR proposes four fixes:
- Allows you to try it even on undefined platforms.
- Supports NRF52
- It also works with NodeRED 3.1.
- When using Japanese, the characters are garbled on the console, so if it is Japanese, switch the console to English mode.

Thank you,

### CODE REVIEW

**Comment by ralphwetzel** [comment]
Thank you for this contribution. I can follow most of your proposals - yet had a few comments.
Feedback welcome!

**Comment by NextWorldLab** [comment]
thank you for your reply. This repository is very important for using Node-RED MCU.
Even if a new device was registered in Moddable, it was not updated.
I would like to help as much as possible, so please leave a comment.
Thank you.

**Comment by ralphwetzel** [comment]
> I would like to help as much as possible, so please leave a comment.

Your contribution is highly appreciated.
If you adapt the two topics according to my comments (given above), I'd be happy to merge your PR & release a new version shortly after - that has support for all known platforms.

**Comment by NextWorldLab** [comment]
I split it up and made a pull request.
Thank you.

https://github.com/ralphwetzel/node-red-mcu-plugin/pull/42
https://github.com/ralphwetzel/node-red-mcu-plugin/pull/43

**Pull request closed without merging**
